<?php

//$data=$block->_preparelayout();
//echo $this->getRedirectUrl();
echo "Operation Performed Row Deleted";
//$this->getFrontController()->getResponse()->setRedirect($this->getBaseUrl());
//exit();
//header("Refresh:2; location:$this->getUrl()");
//$url=$this->getUrl()."excellence/hello/world";
//echo $url;
//$this->_redirect($url);
//$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$redirect = $objectManager->get('\Magento\Framework\App\Response\Http');
//$redirect->setRedirect($url);
//$this->_redirectUrl('http://127.0.0.1/magento2-2.1.8/excellence/hello/world');
//echo $this->get;
?>